Add patches for build failure
 - Resolves kata-agent compilation failures, e.g.

        Compiling kata-agent v0.1.0 (/home/vagrant/rpmbuild/BUILD/kata-containers-2.1.1/src/agent)
        error: field is never read: `ifaces`
          --> src/network.rs:20:5
           |
        20 |     ifaces: HashMap<String, Interface>,
           |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |
           = note: `-D dead-code` implied by `-D warnings`
        note: `Network` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
          --> src/network.rs:18:10
           |
        18 | #[derive(Debug, Default)]
           |          ^^^^^
           = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)error: field is never read: `routes`
          --> src/network.rs:21:5
           |
        21 |     routes: Vec<Route>,
           |     ^^^^^^^^^^^^^^^^^^
           |
        note: `Network` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
          --> src/network.rs:18:10
           |
        18 | #[derive(Debug, Default)]
           |          ^^^^^
           = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)error: could not compile `kata-agent` due to 2 previous errors
        make: *** [target/x86_64-unknown-linux-gnu/release/kata-agent] Error 101
        error: Bad exit status from /var/tmp/rpm-tmp.GalblM (%build)

 - Resolves erroneous append of '-dirty' to commit in kata-runtime command execution.

 - Add missing logic in specfile.